<?php

/**
 * Created by IntelliJ IDEA.
 * User: Kayode
 * Date: 9/27/2018
 * Time: 6:27 PM
 */
namespace App\Repository;
class StudentRepository extends Repository
{
    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
